#!/bin/bash
# "test: yes (jUnit tests for java and javascript, integration tests)"
# "code quality checks: yes (findbugs, pmd, checkstyle)"
# "deploy: no deploy"
# "intent of using: production"
# "minification: yes"
# "we can modify server port for protractor e2e tests by passing argument "-Dprotractor.port=_port_number_"
mvn clean verify -Pprod $1
