#!/bin/bash
# "test: yes (jUnit tests for java and javascript, integration tests)"
# "code quality checks: yes (findbugs, pmd, checkstyle)"
# "deploy: no deploy"
# "intent of using: production"
# "minification: yes"
mvn clean verify -Pprod $1
